"""Gitea/Forgejo forge client — async httpx REST API.

Works with any self-hosted Gitea or Forgejo instance. The base URL is
derived from the ForgeInfo host (e.g. https://git.example.com).

Token resolution order:
  1. GITEA_TOKEN env var
  2. FORGEJO_TOKEN env var
  3. Raise AuthError with a helpful message

Note: Gitea and Forgejo share an identical REST API surface, so a single
implementation covers both.
"""

from __future__ import annotations

import logging
import os
from datetime import datetime
from typing import Any

import httpx

from radioactive_ralph.forge.base import CIState, ForgeCI, ForgeClient, ForgeInfo, ForgePR, PRCreateParams

logger = logging.getLogger(__name__)


class AuthError(Exception):
    """Raised when no Gitea/Forgejo token can be found."""


def _discover_gitea_token() -> str:
    """Discover a Gitea/Forgejo token from the environment.

    Returns:
        Description of return value.

    Raises:
        AuthError: If no Gitea/Forgejo token is found.

    """
    for var in ("GITEA_TOKEN", "FORGEJO_TOKEN"):
        if tok := os.environ.get(var):
            logger.debug("Gitea token from %s", var)
            return tok
    raise AuthError(
        "No Gitea/Forgejo token found. "
        "Set GITEA_TOKEN or FORGEJO_TOKEN."
    )


def _parse_status(status: str) -> CIState:
    """Autogenerated docstring.

    Args:
        status: Description of status.

    Returns:
        Description of return value.

    """
    mapping = {
        "success": CIState.SUCCESS,
        "failure": CIState.FAILURE,
        "error": CIState.FAILURE,
        "pending": CIState.PENDING,
        "running": CIState.RUNNING,
        "cancelled": CIState.CANCELLED,
        "skipped": CIState.SKIPPED,
    }
    return mapping.get(status, CIState.UNKNOWN)


class GiteaForge(ForgeClient):
    """Gitea/Forgejo implementation of ForgeClient.

    Gitea and Forgejo expose identical REST APIs, so this class handles both.
    Tested against Gitea 1.21+ and Forgejo 7.0+.

    Args:
        info: Parsed forge metadata (host, slug, forge_type).
        token: API token. If omitted, discovered from env vars.
    """

    def __init__(self, info: ForgeInfo, token: str | None = None) -> None:
        """Autogenerated docstring.

        Args:
            info: Description of info.
            token: Description of token.

        Returns:
            Description of return value.

        """
        super().__init__(info)
        self._token = token or _discover_gitea_token()
        self._http: httpx.AsyncClient | None = None

    def _make_http(self) -> httpx.AsyncClient:
        """Create a new authenticated httpx.AsyncClient.

        Returns:
            The configured AsyncClient.
        """
        return httpx.AsyncClient(
            base_url=self.info.api_base_url,
            headers={"Authorization": f"token {self._token}"},
            timeout=30.0,
        )

    async def _open(self) -> None:
        """Autogenerated docstring.

        Returns:
            Description of return value.

        """
        self._http = self._make_http()

    async def _close(self) -> None:
        """Autogenerated docstring.

        Returns:
            Description of return value.

        """
        if self._http:
            await self._http.aclose()
            self._http = None

    def _c(self) -> httpx.AsyncClient:
        """Autogenerated docstring.

        Returns:
            Description of return value.

        """
        assert self._http, "Use as async context manager"
        return self._http

    async def _get(self, path: str, **params: Any) -> Any:
        """Autogenerated docstring.

        Args:
            path: Description of path.

        Returns:
            Description of return value.

        """
        resp = await self._c().get(path, params=params)
        resp.raise_for_status()
        return resp.json()

    async def _post(self, path: str, json: dict[str, Any]) -> Any:
        """Autogenerated docstring.

        Args:
            path: Description of path.
            json: Description of json.

        Returns:
            Description of return value.

        """
        resp = await self._c().post(path, json=json)
        resp.raise_for_status()
        return resp.json()

    def _parse_pr(self, raw: dict[str, Any]) -> ForgePR:
        """Autogenerated docstring.

        Args:
            raw: Description of raw.

        Returns:
            Description of return value.

        """
        updated_raw = raw.get("updated_at", "")
        updated_at = (
            datetime.fromisoformat(updated_raw.replace("Z", "+00:00"))
            if updated_raw else datetime.now()
        )
        head = raw.get("head", {})
        return ForgePR(
            number=raw["number"],
            title=raw["title"],
            author=raw.get("user", {}).get("login", "unknown"),
            branch=head.get("label", head.get("ref", "")),
            head_sha=head.get("sha", ""),
            is_draft=raw.get("draft", False),
            url=raw.get("html_url", ""),
            updated_at=updated_at,
        )

    async def list_prs(self, state: str = "open") -> list[ForgePR]:
        """List pull requests for the repo.

        Args:
            state: Filter by state ("open", "closed", "all").

        Returns:
            List of normalised ForgePR objects.
        """
        raw = await self._get(
            f"/repos/{self.info.slug}/pulls",
            state=state, limit=50,
        )
        return [self._parse_pr(r) for r in raw]

    async def get_pr_ci(self, pr: ForgePR) -> ForgeCI:
        """Get CI status for the PR's head commit.

        Queries the Gitea commit statuses API, returning the aggregate state.

        Args:
            pr: The pull request to check.

        Returns:
            Normalised ForgeCI with aggregate state.
        """
        if not pr.head_sha:
            return ForgeCI(state=CIState.UNKNOWN)
        try:
            data = await self._get(
                f"/repos/{self.info.slug}/commits/{pr.head_sha}/statuses",
                limit=20,
            )
        except httpx.HTTPStatusError:
            return ForgeCI(state=CIState.UNKNOWN)

        if not data:
            return ForgeCI(state=CIState.UNKNOWN)

        states = [_parse_status(s.get("status", "")) for s in data]
        details = [{"name": s.get("context", ""), "state": st.value}
                   for s, st in zip(data, states, strict=False)]

        if any(s == CIState.FAILURE for s in states):
            return ForgeCI(state=CIState.FAILURE, details=details)
        if any(s in (CIState.PENDING, CIState.RUNNING) for s in states):
            return ForgeCI(state=CIState.PENDING, details=details)
        if all(s in (CIState.SUCCESS, CIState.SKIPPED) for s in states):
            return ForgeCI(state=CIState.SUCCESS, details=details)
        return ForgeCI(state=CIState.UNKNOWN, details=details)

    async def get_pr_reviews(self, pr: ForgePR) -> ForgePR:
        """Fetch and aggregate reviews for a Gitea pull request.

        Considers only the latest review state for each unique reviewer.

        Args:
            pr: The pull request to fetch reviews for.

        Returns:
            The updated ForgePR object.
        """
        # Gitea API: /repos/{owner}/{repo}/pulls/{index}/reviews
        try:
            reviews = await self._get(f"/repos/{self.info.slug}/pulls/{pr.number}/reviews")
            if not isinstance(reviews, list):
                return pr

            # Group by reviewer and keep the latest state
            latest_reviews = {}
            for r in reviews:
                user_id = r.get("user", {}).get("id")
                if user_id:
                    # Gitea returns reviews in chronological order, so just overwrite
                    latest_reviews[user_id] = r.get("state")

            states = list(latest_reviews.values())
            pr.review_count = len(latest_reviews)
            pr.review_approved = any(s == "APPROVED" for s in states)
            pr.changes_requested = any(s == "REQUEST_CHANGES" for s in states)
        except httpx.HTTPStatusError as e:
            logger.debug("Could not fetch reviews for #%d: %s", pr.number, e)
            
        return pr

    async def create_pr(self, params: PRCreateParams) -> ForgePR:
        """Create a pull request.

        Args:
            params: Title, body, head branch, base branch, and draft flag.

        Returns:
            The newly created PR as a ForgePR.
        """
        raw = await self._post(
            f"/repos/{self.info.slug}/pulls",
            json={
                "title": params.title,
                "body": params.body,
                "head": params.head,
                "base": params.base,
            },
        )
        return self._parse_pr(raw)

    async def merge_pr(self, pr: ForgePR) -> bool:
        """Squash-merge a pull request and delete the source branch.

        Args:
            pr: The pull request to merge.

        Returns:
            True if merged successfully, False otherwise.
        """
        try:
            await self._post(
                f"/repos/{self.info.slug}/pulls/{pr.number}/merge",
                json={"Do": "squash", "delete_branch_after_merge": True},
            )
            return True
        except httpx.HTTPStatusError as e:
            logger.warning("Failed to merge #%d: %s", pr.number, e.response.text)
            return False
