sonar.projectKey=jbcom_radioactive-ralph
sonar.organization=jbcom

sonar.python.coverage.reportPaths=artifacts/coverage-*.xml
sonar.python.xunit.reportPath=artifacts/pytest-results-3.13.xml
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12, 3.13
sonar.sources=src
sonar.tests=tests
