"""Tests for PR manager."""

from __future__ import annotations

from datetime import UTC, datetime

import pytest
from pytest_mock import MockerFixture

from radioactive_ralph.models import PRInfo, PRStatus
from radioactive_ralph.pr_manager import extract_pr_url


def test_extract_pr_url_found() -> None:
    """Autogenerated docstring.

    Returns:
        Description of return value.

    """
    output = "Created PR at https://github.com/org/repo/pull/42 successfully"
    assert extract_pr_url(output) == "https://github.com/org/repo/pull/42"


def test_extract_pr_url_not_found() -> None:
    """Autogenerated docstring.

    Returns:
        Description of return value.

    """
    assert extract_pr_url("no url here") is None


def test_pr_info_mergeable_requires_ci() -> None:
    """Autogenerated docstring.

    Returns:
        Description of return value.

    """
    pr = PRInfo(
        repo="test/repo", number=1, title="feat", author="bot",
        branch="feat/x", status=PRStatus.MERGE_READY, ci_passed=False
    )
    assert pr.is_mergeable is False


def test_pr_info_mergeable_when_ready() -> None:
    """Autogenerated docstring.

    Returns:
        Description of return value.

    """
    pr = PRInfo(
        repo="test/repo", number=2, title="feat", author="bot",
        branch="feat/y", status=PRStatus.MERGE_READY, ci_passed=True, is_draft=False
    )
    assert pr.is_mergeable is True


@pytest.mark.asyncio
async def test_classify_pr_uses_forge_client(mocker: MockerFixture) -> None:
    """classify_pr fetches CI and reviews via the ForgeClient abstraction.

    Args:
        mocker: Description of mocker.

    Returns:
        Description of return value.

    """
    from unittest.mock import AsyncMock

    from radioactive_ralph.forge.base import CIState, ForgeCI, ForgePR
    from radioactive_ralph.pr_manager import classify_pr

    forge_pr = ForgePR(
        number=5, title="test", author="bot", branch="feat/z",
        head_sha="abc123", is_draft=False, url="",
        updated_at=datetime.now(UTC),
    )

    mock_forge = mocker.MagicMock()
    mock_forge.get_pr_ci = AsyncMock(return_value=ForgeCI(state=CIState.SUCCESS))
    mock_forge.get_pr_reviews = AsyncMock(return_value=forge_pr)

    result = await classify_pr(forge_pr, mock_forge)
    mock_forge.get_pr_ci.assert_called_once_with(forge_pr)
    mock_forge.get_pr_reviews.assert_called_once()
    assert result.ci is not None
    assert result.ci.passed
