package fixit

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Emit runs Stage 6 — write the plan to disk and return what happened.
// The status comes from the caller (Current / Provisional / Fallback)
// based on Stage 4 + Stage 5 outcomes.
//
// The emitted file ALWAYS has valid plan-format frontmatter so it
// satisfies the shape the plans-first discipline expects, even when
// status is fallback or provisional — other variants gate on the
// status field, not on presence of frontmatter.
func Emit(plansDir, topic string, proposal PlanProposal,
	validation ValidationResult, status PlanStatus,
	intent IntentSpec, rc RepoContext,
) (EmittedPlan, error) {
	if err := os.MkdirAll(plansDir, 0o750); err != nil {
		return EmittedPlan{}, fmt.Errorf("mkdir plans dir: %w", err)
	}
	path := filepath.Join(plansDir, topic+"-advisor.md")
	body := renderReport(topic, proposal, validation, status, intent, rc)
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil { //nolint:gosec // operator repo path
		return EmittedPlan{}, fmt.Errorf("write advisor report: %w", err)
	}
	return EmittedPlan{
		Path:        path,
		Status:      status,
		Proposal:    proposal,
		Validation:  validation,
		Intent:      intent,
		RepoContext: rc,
	}, nil
}

// EmitFallback writes a diagnostic-only plan whose status is
// `fallback`. Used when Stage 4 fails twice or Stage 5 produces a
// failure the operator should see directly.
func EmitFallback(plansDir, topic string, reason string, rawOutput string,
	intent IntentSpec, rc RepoContext,
) (EmittedPlan, error) {
	return Emit(plansDir, topic, PlanProposal{
		Primary:          "blue",
		PrimaryRationale: "Fallback recommendation — fixit could not produce a coherent plan. Blue is the safest read-only default while the operator investigates.",
		Tasks: []Task{
			{Title: "Operator: inspect the Methodology section of this report", Effort: "S", Impact: "L"},
			{Title: "Operator: rerun `radioactive_ralph run --variant fixit --advise` with a clearer --description", Effort: "S", Impact: "M"},
		},
		AcceptanceCriteria: []string{
			"Operator has reviewed the fallback rationale",
			"Operator has decided whether to rerun fixit or pick a variant manually",
			"If rerunning, a non-fallback plan exists",
		},
		Confidence: 0,
	}, ValidationResult{Failures: []string{"fallback: " + reason, "raw: " + truncate(rawOutput, 200)}},
		StatusFallback, intent, rc)
}

// renderReport returns the full markdown file contents.
func renderReport(topic string, p PlanProposal, v ValidationResult,
	status PlanStatus, intent IntentSpec, rc RepoContext,
) string {
	var b strings.Builder
	// Frontmatter — always valid plan format.
	fmt.Fprintln(&b, "---")
	fmt.Fprintf(&b, "title: Fixit advisor report — %s\n", topic)
	fmt.Fprintf(&b, "updated: %s\n", time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintf(&b, "status: %s\n", status)
	fmt.Fprintln(&b, "domain: product")
	fmt.Fprintf(&b, "variant_recommendation: %s\n", p.Primary)
	if p.Alternate != "" {
		fmt.Fprintf(&b, "variant_alternate: %s\n", p.Alternate)
	}
	fmt.Fprintf(&b, "confidence: %d\n", p.Confidence)
	fmt.Fprintln(&b, "---")
	fmt.Fprintln(&b)

	fmt.Fprintf(&b, "# Fixit advisor — %s\n\n", topic)
	fmt.Fprintf(&b, "Generated by `radioactive_ralph run --variant fixit --advise` against `%s` on branch `%s`.\n\n",
		rc.GitRoot, rc.CurrentBranch)

	// Context summary.
	fmt.Fprintln(&b, "## Operator intent")
	fmt.Fprintln(&b)
	if intent.Description != "" {
		fmt.Fprintf(&b, "**Goal:** %s\n\n", intent.Description)
	} else {
		fmt.Fprintln(&b, "_(no operator description provided)_")
		fmt.Fprintln(&b)
	}
	if len(intent.Constraints) > 0 {
		fmt.Fprintln(&b, "**Constraints:**")
		for _, c := range intent.Constraints {
			fmt.Fprintf(&b, "- %s\n", c)
		}
		fmt.Fprintln(&b)
	}

	// Primary + alternate.
	fmt.Fprintf(&b, "## Primary recommendation: `%s-ralph`\n\n", p.Primary)
	fmt.Fprintf(&b, "%s\n\n", p.PrimaryRationale)
	if p.Alternate != "" {
		fmt.Fprintf(&b, "## Alternate: `%s-ralph`\n\n", p.Alternate)
		fmt.Fprintf(&b, "Use the alternate when: %s\n\n", p.AlternateWhen)
	} else {
		fmt.Fprintln(&b, "## Tradeoffs")
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "None. The recommendation is unambiguous given the current state.")
		fmt.Fprintln(&b)
	}

	// Tasks.
	if len(p.Tasks) > 0 {
		fmt.Fprintln(&b, "## Tasks")
		fmt.Fprintln(&b)
		for _, t := range p.Tasks {
			fmt.Fprintf(&b, "- **[%s/%s]** %s\n", t.Effort, t.Impact, t.Title)
		}
		fmt.Fprintln(&b)
	}

	// Acceptance criteria.
	if len(p.AcceptanceCriteria) > 0 {
		fmt.Fprintln(&b, "## Acceptance criteria")
		fmt.Fprintln(&b)
		for _, c := range p.AcceptanceCriteria {
			fmt.Fprintf(&b, "- [ ] %s\n", c)
		}
		fmt.Fprintln(&b)
	}

	// Validation report.
	fmt.Fprintln(&b, "## Validation")
	fmt.Fprintln(&b)
	if v.Passed {
		fmt.Fprintln(&b, "All validation rules passed. This plan has `status: current` and will satisfy the plans-first gate for other variants.")
	} else {
		fmt.Fprintf(&b, "Status: `%s`. Failures:\n\n", status)
		for _, f := range v.Failures {
			fmt.Fprintf(&b, "- %s\n", f)
		}
		fmt.Fprintln(&b)
		if status == StatusProvisional {
			fmt.Fprintln(&b, "_Other variants will refuse to run on a provisional plan. Promote it to `status: current` in the frontmatter once you've addressed the failures above._")
		}
	}
	fmt.Fprintln(&b)

	// Methodology — what fixit did to produce this.
	fmt.Fprintln(&b, "## Methodology")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "This plan was produced by fixit-ralph's six-stage pipeline:")
	fmt.Fprintln(&b, "1. Operator intent capture (--description, --topic, constraints)")
	fmt.Fprintln(&b, "2. Deterministic repo exploration (git log, docs scan, PR/issue scrape, inventory)")
	fmt.Fprintln(&b, "3. Rule-based variant scoring (no LLM)")
	fmt.Fprintln(&b, "4. Constrained Claude analysis (sonnet subprocess, JSON-schema output)")
	fmt.Fprintln(&b, "5. Validation gates (variant exists, safety floors compatible, criteria measurable, files exist, confidence floor)")
	fmt.Fprintln(&b, "6. Plan emission (this file)")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "See `docs/design/fixit-plan-pipeline.md` for the pipeline contract.\n")
	return b.String()
}
