package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// runAdvisor is the fixit-only code path that walks the repo + plans
// state and writes a variant recommendation to
// .radioactive-ralph/plans/<topic>-advisor.md. plansOK reports whether
// the plans-first gate passed (i.e. fixit was invoked with --advise
// despite a valid plans setup) or failed (fixit is fallback advisor).
//
// M2 shape: writes a structured report stub reflecting the detected
// repo state (git root, current branch, plans presence). M3 replaces
// the stub analysis with a real LLM-backed scan that considers the
// codebase contents + any operator-provided description and produces
// a genuine primary+alternate recommendation.
//
// Exit behavior:
//   - Writes the report unconditionally. The report is always useful
//     even in stub form because it records the repo state at the
//     moment of advisor invocation and documents the recommended
//     next step.
//   - With --auto-handoff and a single unambiguous recommendation,
//     prints a follow-up command (actual spawn lands in M3 alongside
//     session pool).
func (c *RunCmd) runAdvisor(repo string, plansOK bool) error {
	topic := c.Topic
	if topic == "" {
		topic = "general"
	}
	// Sanitize topic to a safe slug — strip anything that would upset
	// a filename across macOS/Linux/WSL.
	topic = sanitizeTopic(topic)

	plansDir := filepath.Join(repo, ".radioactive-ralph", "plans")
	if err := os.MkdirAll(plansDir, 0o750); err != nil {
		return fmt.Errorf("mkdir plans dir: %w", err)
	}
	reportPath := filepath.Join(plansDir, topic+"-advisor.md")

	recommendation := recommendVariant(plansOK)
	report := renderAdvisorReport(repo, topic, plansOK, recommendation)
	if err := os.WriteFile(reportPath, []byte(report), 0o644); err != nil { //nolint:gosec // operator-owned repo path
		return fmt.Errorf("write advisor report: %w", err)
	}
	fmt.Printf("ralph: fixit advisor report written to %s\n", reportPath)
	fmt.Printf("  primary recommendation: %s\n", recommendation.Primary)
	if recommendation.Alternate != "" {
		fmt.Printf("  alternate: %s (use when: %s)\n",
			recommendation.Alternate, recommendation.AlternateReason)
	}
	if c.AutoHandoff {
		if recommendation.Alternate != "" {
			fmt.Println("ralph: --auto-handoff skipped — recommendation has tradeoffs")
			return nil
		}
		fmt.Printf("ralph: --auto-handoff would invoke `ralph run --variant %s` once M3's session pool ships\n",
			recommendation.Primary)
	}
	return nil
}

// Recommendation captures what fixit decided about this codebase.
type Recommendation struct {
	Primary         string // variant name like "grey" or "green"
	Rationale       string // one-sentence justification
	Alternate       string // empty when there's no tradeoff
	AlternateReason string // when the operator should pick the alternate
}

// recommendVariant is the M2 stub. Without a real LLM scan it uses
// the plans-state signal only: missing plans → grey (safe mechanical
// cleanup) + green (full loop) as alternate; valid plans → green
// unambiguous. M3 replaces this with real analysis.
func recommendVariant(plansOK bool) Recommendation {
	if !plansOK {
		return Recommendation{
			Primary:         "grey",
			Rationale:       "No valid plans/index.md yet — start with grey-ralph's mechanical hygiene sweep to get governance and frontmatter in order before tackling features.",
			Alternate:       "green",
			AlternateReason: "operator already knows what feature work to tackle and prefers to iterate on it directly rather than clean up first",
		}
	}
	return Recommendation{
		Primary:   "green",
		Rationale: "Plans are in place; green-ralph is the default full-power orchestrator.",
	}
}

// renderAdvisorReport returns the markdown for the advisor output
// file. Uses frontmatter compatible with the plans-first schema so the
// file itself satisfies the gate it was meant to answer.
func renderAdvisorReport(repo, topic string, plansOK bool, rec Recommendation) string {
	var b strings.Builder
	fmt.Fprintf(&b, "---\n")
	fmt.Fprintf(&b, "title: Fixit advisor report — %s\n", topic)
	fmt.Fprintf(&b, "updated: %s\n", time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintf(&b, "status: advisory\n")
	fmt.Fprintf(&b, "domain: product\n")
	fmt.Fprintf(&b, "variant_recommendation: %s\n", rec.Primary)
	fmt.Fprintf(&b, "---\n\n")

	fmt.Fprintf(&b, "# Fixit advisor — %s\n\n", topic)
	fmt.Fprintf(&b, "Generated by `ralph run --variant fixit --advise` on repo `%s`.\n\n", repo)

	if !plansOK {
		b.WriteString("## Plans state\n\n")
		b.WriteString("`.radioactive-ralph/plans/index.md` is missing or lacks YAML frontmatter. ")
		b.WriteString("Fixit was invoked as the plans-first fallback advisor for exactly this case — every ")
		b.WriteString("non-Fixit variant refuses to run until this file is in place.\n\n")
	} else {
		b.WriteString("## Plans state\n\nValid plans/index.md detected. Fixit was invoked explicitly via `--advise`.\n\n")
	}

	fmt.Fprintf(&b, "## Primary recommendation: `%s-ralph`\n\n", rec.Primary)
	b.WriteString(rec.Rationale)
	b.WriteString("\n\n")

	if rec.Alternate != "" {
		fmt.Fprintf(&b, "## Alternate: `%s-ralph`\n\n", rec.Alternate)
		fmt.Fprintf(&b, "Use %s-ralph instead when: %s.\n\n",
			rec.Alternate, rec.AlternateReason)
	} else {
		b.WriteString("## Tradeoffs\n\nNone. The recommendation is unambiguous for this codebase state.\n\n")
	}

	b.WriteString("## Next steps\n\n")
	fmt.Fprintf(&b, "```bash\nralph run --variant %s --foreground\n```\n\n", rec.Primary)
	b.WriteString("Or, to have Fixit bang on the problem directly instead of delegating:\n\n")
	b.WriteString("```bash\nralph run --variant fixit --foreground\n```\n\n")
	b.WriteString("## About this report\n\n")
	b.WriteString("Fixit Ralph is the only variant permitted to recommend peers. This report was ")
	b.WriteString("written by Fixit's advisor mode. The M2 shape is a state-driven stub; M3 adds a ")
	b.WriteString("real LLM-backed scan that considers codebase contents + any operator description ")
	b.WriteString("(passed via `--topic` and context files).\n")
	return b.String()
}

// sanitizeTopic returns a lowercase slug safe for filenames on all
// supported platforms. Keeps [a-z0-9-_], collapses runs of separators.
func sanitizeTopic(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	var b strings.Builder
	lastSep := true
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			lastSep = false
		case r == '-' || r == '_':
			if !lastSep {
				b.WriteRune(r)
				lastSep = true
			}
		default:
			if !lastSep {
				b.WriteRune('-')
				lastSep = true
			}
		}
	}
	result := strings.Trim(b.String(), "-_")
	if result == "" {
		return "general"
	}
	return result
}
