#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
SOURCE="$TMP/dist"
ASSETS="$TMP/assets"
mkdir -p "$SOURCE/homebrew/Casks" "$SOURCE/scoop/bucket" "$ASSETS"
printf 'cli exact\n' > "$SOURCE/homebrew/Casks/radioactive-ralph.rb"
printf '{"version":"1.2.3"}\n' > "$SOURCE/scoop/bucket/radioactive-ralph.json"
{
  printf '%064d  radioactive-ralph_1.2.3_darwin_arm64.dmg\n' 0
  printf '%064d  radioactive-ralph_1.2.3_darwin_amd64.dmg\n' 1
} > "$ASSETS/gui-checksums.txt"

cat > "$TMP/gh" <<'FAKEGH'
#!/usr/bin/env bash
set -euo pipefail
[[ "${1:-}" == release ]]
case "${2:-}" in
  view)
    find "$FAKE_ASSETS" -maxdepth 1 -type f -exec basename {} \; | sort
    ;;
  download)
    pattern=""
    output=""
    while (($#)); do
      case "$1" in
        --pattern) pattern="${2:?}"; shift 2 ;;
        --output) output="${2:?}"; shift 2 ;;
        *) shift ;;
      esac
    done
    cp "$FAKE_ASSETS/$pattern" "$output"
    ;;
  upload)
    shift 3
    while (($#)); do
      case "$1" in
        --repo) shift 2 ;;
        *) cp "$1" "$FAKE_ASSETS/$(basename "$1")"; shift ;;
      esac
    done
    ;;
  *) exit 1 ;;
esac
FAKEGH
chmod +x "$TMP/gh"
cat > "$TMP/cosign" <<'FAKECOSIGN'
#!/usr/bin/env bash
set -euo pipefail
[[ "${FAKE_COSIGN_FAILURE:-0}" != 1 ]]
if [[ "$1" == sign-blob ]]; then
  while (($#)); do
    if [[ "$1" == --bundle ]]; then
      printf '{"fixture":true}\n' > "$2"
      exit 0
    fi
    shift
  done
fi
[[ "$1" == verify-blob ]]
FAKECOSIGN
chmod +x "$TMP/cosign"
cat > "$TMP/tar" <<'FAKETAR'
#!/usr/bin/env bash
set -euo pipefail
args=()
for arg in "$@"; do
  case "$arg" in
    --sort=*|--mtime=*|--owner=*|--group=*|--numeric-owner) ;;
    *) args+=("$arg") ;;
  esac
done
exec /usr/bin/tar "${args[@]}"
FAKETAR
chmod +x "$TMP/tar"

run_prepare() {
  FAKE_ASSETS="$ASSETS" \
  GH_BIN="$TMP/gh" \
  COSIGN_BIN="$TMP/cosign" \
  TAR_BIN="$TMP/tar" \
  RELEASE_GH_TOKEN=fake \
  SOURCE_ROOT="$SOURCE" \
    bash "$ROOT/scripts/ci/prepare_package_manifests_bundle.sh" 1.2.3
}

run_prepare
test -f "$ASSETS/package-manifests.tar.gz"
test -f "$ASSETS/package-manifests.tar.gz.sigstore.json"
first_sha="$(shasum -a 256 "$ASSETS/package-manifests.tar.gz" | awk '{print $1}')"
run_prepare
[[ "$(shasum -a 256 "$ASSETS/package-manifests.tar.gz" | awk '{print $1}')" == "$first_sha" ]]

mv "$ASSETS/package-manifests.tar.gz.sigstore.json" "$TMP/bundle"
if run_prepare >/dev/null 2>&1; then
  echo "expected partial durable package bundle to fail" >&2
  exit 1
fi
mv "$TMP/bundle" "$ASSETS/package-manifests.tar.gz.sigstore.json"

printf 'changed\n' > "$SOURCE/homebrew/Casks/radioactive-ralph.rb"
if run_prepare >/dev/null 2>&1; then
  echo "expected regenerated byte mismatch to fail" >&2
  exit 1
fi
printf 'cli exact\n' > "$SOURCE/homebrew/Casks/radioactive-ralph.rb"
if FAKE_COSIGN_FAILURE=1 run_prepare >/dev/null 2>&1; then
  echo "expected existing bundle signature failure to fail" >&2
  exit 1
fi

echo "package manifest durable bundle tests: ok"
