"""Pydantic models for radioactive_ralph state, work items, and agent runs."""

from __future__ import annotations

from datetime import UTC, datetime
from enum import Enum
from pathlib import Path

from pydantic import BaseModel, Field


class PRStatus(str, Enum):
    """Classification of a pull request's current state."""

    MERGE_READY = "merge_ready"
    NEEDS_REVIEW = "needs_review"
    NEEDS_FIXES = "needs_fixes"
    CI_FAILING = "ci_failing"
    IN_PROGRESS = "in_progress"
    STALE = "stale"
    DRAFT = "draft"


class ReviewSeverity(str, Enum):
    """Severity level for a review finding."""

    ERROR = "error"
    WARNING = "warning"
    SUGGESTION = "suggestion"
    NITPICK = "nitpick"


class WorkPriority(int, Enum):
    """Priority levels for work items. Lower number = higher priority."""

    CI_FAILURE = 1
    PR_FIXES = 2
    DOC_SWEEP = 3
    MISSING_FILES = 4
    STATE_NEXT = 5
    DESIGN_FEATURE = 6
    POLISH = 7


class PRInfo(BaseModel):
    """Representation of a GitHub pull request."""

    repo: str
    number: int
    title: str
    author: str
    branch: str
    status: PRStatus
    ci_passed: bool = False
    review_count: int = 0
    has_unresolved_comments: bool = False
    is_draft: bool = False
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    url: str = ""

    @property
    def is_mergeable(self) -> bool:
        """Autogenerated docstring.

        Returns:
            Description of return value.

        """
        return self.status == PRStatus.MERGE_READY and self.ci_passed and not self.is_draft


class ReviewFinding(BaseModel):
    """A single finding from a code review."""

    severity: ReviewSeverity
    file: str
    line: int | None = None
    issue: str
    fix: str


class ReviewResult(BaseModel):
    """Result of an AI code review."""

    pr: PRInfo
    findings: list[ReviewFinding] = Field(default_factory=list)
    approved: bool = False
    summary: str = ""

    @property
    def has_blocking_issues(self) -> bool:
        """Autogenerated docstring.

        Returns:
            Description of return value.

        """
        return any(f.severity == ReviewSeverity.ERROR for f in self.findings)


class WorkItem(BaseModel):
    """A unit of work to be executed by an agent."""

    id: str
    repo_path: str
    description: str
    priority: WorkPriority
    source: str = ""
    context: str = ""
    timeout_seconds: int = 1800
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    @property
    def repo_name(self) -> str:
        """Autogenerated docstring.

        Returns:
            Description of return value.

        """
        return Path(self.repo_path).name


class AgentResult(BaseModel):
    """Result of a Claude Code agent execution."""

    task_id: str
    repo_path: str
    output: str = ""
    returncode: int = -1
    pr_url: str | None = None
    duration_seconds: float = 0.0
    completed_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    @property
    def succeeded(self) -> bool:
        """Autogenerated docstring.

        Returns:
            Description of return value.

        """
        return self.returncode == 0


class AgentRun(BaseModel):
    """Tracking record for an active or completed agent run."""

    task: WorkItem
    started_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    result: AgentResult | None = None

    @property
    def is_active(self) -> bool:
        """Autogenerated docstring.

        Returns:
            Description of return value.

        """
        return self.result is None


class OrchestratorState(BaseModel):
    """Top-level durable state for the orchestrator."""

    active_runs: list[AgentRun] = Field(default_factory=list)
    completed_runs: list[AgentRun] = Field(default_factory=list)
    merge_queue: list[PRInfo] = Field(default_factory=list)
    work_queue: list[WorkItem] = Field(default_factory=list)
    last_scan: datetime | None = None
    last_discovery: datetime | None = None
    cycle_count: int = 0


# RadioactiveRalphConfig lives in radioactive_ralph.config — import it from there.
# This module contains only work-item and state models, not settings.
