#!/usr/bin/env bash
# Publish one atomic package PR containing the exact Homebrew CLI cask and Scoop
# manifest generated by pinned GoReleaser plus the GUI cask derived from the
# signed consolidated GUI checksum manifest.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERSION="${1:?usage: publish-cli-manifests.sh <version>}"
SOURCE_ROOT="${SOURCE_ROOT:-dist}"
CLI_CASK="${SOURCE_ROOT}/homebrew/Casks/radioactive-ralph.rb"
SCOOP_MANIFEST="${SOURCE_ROOT}/scoop/bucket/radioactive-ralph.json"
GUI_CASK="${SOURCE_ROOT}/homebrew/Casks/radioactive-ralph-gui.rb"
PKGS="${PKGS_REPO:-jbcom/pkgs}"
PKGS_CLONE_URL="${PKGS_CLONE_URL:-https://x-access-token@github.com/${PKGS}.git}"
GH_BIN="${GH_BIN:-gh}"
COSIGN_BIN="${COSIGN_BIN:-cosign}"
RELEASE_REPO="${RELEASE_REPO:-jbcom/radioactive-ralph}"
PKGS_GH_TOKEN="${PKGS_GH_TOKEN:-}"
RELEASE_GH_TOKEN="${RELEASE_GH_TOKEN:-}"
BASE_BRANCH="chore/update-radioactive-ralph-${VERSION}"
BRANCH="${PACKAGE_BRANCH:-$BASE_BRANCH}"

[[ -n "$PKGS_GH_TOKEN" ]] || {
  echo "publish-cli-manifests: PKGS_GH_TOKEN is required" >&2
  exit 1
}
[[ -n "$RELEASE_GH_TOKEN" ]] || {
  echo "publish-cli-manifests: RELEASE_GH_TOKEN is required" >&2
  exit 1
}

if [[ "${RESOLVE_PACKAGE_ATTEMPT_BRANCH:-0}" == "1" &&
      -z "${PACKAGE_BRANCH:-}" ]]; then
  open_prs="$(GH_TOKEN="$PKGS_GH_TOKEN" "$GH_BIN" pr list --repo "$PKGS" \
    --state open --limit 1000 \
    --json baseRefName,headRefName,headRepositoryOwner,isCrossRepository)"
  open_branches="$(jq -r --arg base "$BASE_BRANCH" --arg owner "${PKGS%%/*}" \
    '.[] | select(
      .baseRefName == "main" and
      (.headRefName == $base or (
        (.headRefName | startswith($base + "-attempt-")) and
        (.headRefName | ltrimstr($base + "-attempt-") |
          test("^[1-9][0-9]*$"))
      )) and
      .headRepositoryOwner.login == $owner and .isCrossRepository == false
    ) | .headRefName' <<<"$open_prs")"
  open_count="$(grep -c . <<<"$open_branches" || true)"
  if [[ "$open_count" == 1 ]]; then
    BRANCH="$open_branches"
  elif [[ "$open_count" != 0 ]]; then
    echo "publish-cli-manifests: ambiguous open release attempt branches" >&2
    exit 1
  else
    merged_count="$(GH_TOKEN="$PKGS_GH_TOKEN" "$GH_BIN" pr list --repo "$PKGS" \
      --state merged --limit 1000 \
      --json baseRefName,headRefName,headRepositoryOwner,isCrossRepository |
      jq --arg base "$BASE_BRANCH" --arg owner "${PKGS%%/*}" \
        '[.[] | select(
          .baseRefName == "main" and
          (.headRefName == $base or (
            (.headRefName | startswith($base + "-attempt-")) and
            (.headRefName | ltrimstr($base + "-attempt-") |
              test("^[1-9][0-9]*$"))
          )) and
          .headRepositoryOwner.login == $owner and .isCrossRepository == false
        )] | length')"
    if [[ "$merged_count" != 0 ]]; then
      BRANCH="${BASE_BRANCH}-attempt-$((merged_count + 1))"
    fi
  fi
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
archive="$WORK/package-manifests.tar.gz"
bundle="$WORK/package-manifests.tar.gz.sigstore.json"
release="$(GH_TOKEN="$RELEASE_GH_TOKEN" "$GH_BIN" release view "v${VERSION}" \
  --repo "$RELEASE_REPO" --json assets)"
download_release_asset() {
  local asset="$1" output="$2" api_url
  api_url="$(jq -er --arg name "$asset" \
    '.assets[] | select(.name == $name) | .apiUrl' <<<"$release")"
  GH_TOKEN="$RELEASE_GH_TOKEN" "$GH_BIN" api \
    -H 'Accept: application/octet-stream' "$api_url" > "$output"
}
download_release_asset package-manifests.tar.gz "$archive"
download_release_asset package-manifests.tar.gz.sigstore.json "$bundle"
"$COSIGN_BIN" verify-blob "$archive" --bundle "$bundle" \
  --certificate-identity \
  "https://github.com/${RELEASE_REPO}/.github/workflows/release.yml@refs/tags/v${VERSION}" \
  --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
  >/dev/null
listing="$(tar -tzf "$archive" | LC_ALL=C sort)"
expected="$(printf '%s\n' \
  Casks/radioactive-ralph.rb \
  Casks/radioactive-ralph-gui.rb \
  bucket/radioactive-ralph.json | LC_ALL=C sort)"
[[ "$listing" == "$expected" ]] || {
  echo "publish-cli-manifests: signed package archive member set is not exact" >&2
  exit 1
}
mkdir -p "$(dirname "$CLI_CASK")" "$(dirname "$SCOOP_MANIFEST")"
tar -xzf "$archive" -C "$WORK"
cp "$WORK/Casks/radioactive-ralph.rb" "$CLI_CASK"
cp "$WORK/Casks/radioactive-ralph-gui.rb" "$GUI_CASK"
cp "$WORK/bucket/radioactive-ralph.json" "$SCOOP_MANIFEST"
ASKPASS="$WORK/askpass.sh"
printf '#!/bin/sh\nprintf "%%s" "%s"\n' "$PKGS_GH_TOKEN" > "$ASKPASS"
chmod 0700 "$ASKPASS"
export GIT_ASKPASS="$ASKPASS" GIT_TERMINAL_PROMPT=0

git clone --depth 1 "$PKGS_CLONE_URL" "$WORK/pkgs"
git -C "$WORK/pkgs" checkout -B "$BRANCH"
mkdir -p "$WORK/pkgs/Casks" "$WORK/pkgs/bucket"
cp "$CLI_CASK" "$WORK/pkgs/Casks/radioactive-ralph.rb"
cp "$GUI_CASK" "$WORK/pkgs/Casks/radioactive-ralph-gui.rb"
cp "$SCOOP_MANIFEST" "$WORK/pkgs/bucket/radioactive-ralph.json"
(
  cd "$WORK/pkgs"
  node scripts/generate-directory.mjs
)
git -C "$WORK/pkgs" add \
  Casks/radioactive-ralph.rb \
  Casks/radioactive-ralph-gui.rb \
  bucket/radioactive-ralph.json \
  src/data/directory/directory.json

if git -C "$WORK/pkgs" diff --cached --quiet --exit-code; then
  echo "publish-cli-manifests: radioactive-ralph ${VERSION} is already exact on ${PKGS} main"
  exit 0
fi

git -C "$WORK/pkgs" \
  -c user.name=jbcom-bot \
  -c user.email=noreply@jonbogaty.com \
  commit -m "chore: update radioactive-ralph packages to ${VERSION}"
(
  cd "$WORK/pkgs"
  bash "$SCRIPT_DIR/macos/push-version-branch.sh" "$BRANCH"
)

if ! GH_TOKEN="$PKGS_GH_TOKEN" "$GH_BIN" pr create --repo "$PKGS" --base main --head "$BRANCH" \
  --title "chore: update radioactive-ralph packages to ${VERSION}" \
  --body "Automated atomic Homebrew CLI/GUI cask and Scoop manifest update for radioactive-ralph ${VERSION}." \
  2>"$WORK/pr-error.log"; then
  if grep -qi "already exists" "$WORK/pr-error.log"; then
    echo "publish-cli-manifests: PR already open for ${BRANCH} — nothing to do"
  else
    cat "$WORK/pr-error.log" >&2
    exit 1
  fi
fi
echo "publish-cli-manifests: manifests published for ${VERSION}"
